routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/


//Route::get('/jeux', 'ListeJeux@index')->name('jeux');
Route::resource('jeux', 'ListeJeux');
Route::resource('admin','Admin');

Route::get('apropos','HomeController@about');
Route::get('about','HomeController@about');
Route::get('contact','HomeController@contact');
Route::get('/','HomeController@index');
Route::get('/login','HomeController@login');
Route::resource('comm', 'CommentaireController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();



//Route::get('/home', 'HomeController@index')->name('home');

app/Models/Jeux.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Jeux extends Model
{
    //
    protected $table = 'jeux';
    public $timestamps = false;

    function tags() {
        return $this->belongsToMany(Tag::class);
    }

    function commentaires() {
        return $this->hasMany(Commentaire::class);
    }

}

resources/views/jeux/admin.blade.php
@extends('layouts.header')
@section("content")




<div class="container">
    <h1>Liste des jeux</h1>

    <p style="margin-bottom: 10px;"><a href="{{route('jeux.create')}}" class="btn btn-success">Ajouter un Jeu</a></p>


    @if(!empty($jeux))
        <br>
        <div class="row">
            @foreach($jeux as $jeu)
                @if($jeu['id'] % 2 == 1 && $jeu['id'] != 1)
        </div>
        <br>
        <div class="row">
            @endif
            <div class="col">
                <div class="card" style="width:400px">
                    <img class="card-img-top" src="{{$jeu['urlimg']}}"  style="height:100px;object-fit: cover;" alt="Card image">
                    <div class="card-body">
                        <h4 class="card-title">{{$jeu['nom']}}</h4>
                        <h5>Année Sortie : {{$jeu['annee_sortie']}}</h5>
                        <h5>Age Mini : {{$jeu['age_min']}} ans</h5>
                        <h5>Nombre joueurs : {{$jeu['min_max_joueur']}}</h5>
                        <h5>Durée : {{$jeu['min_max_duree']}}</h5>
                        <p class="card-text">{{$jeu['description']}}</p>
                        <a class="btn btn-secondary" href="{{route('jeux.show',$jeu['id'])}}">Infos</a> <a class="btn btn-warning" href="{{route('jeux.show',$jeu['id'])}}/edit">Éditer</a> <a class="btn btn-danger" href="{{route('jeux.show',$jeu['id'])}}?action=delete">Supprimer</a>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    @else
        <h2>Aucun jeu d'entré !</h2>
    @endif
</div>
@endsection

resources/views/jeux/create.blade.php
{{--
   messages d'erreurs dans la saisie du formulaire.
--}}
@extends('layouts.header')
@section("content")
<div class="container">

@if ($errors->any())
    <div>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
{{--
     formulaire de saisie d'une tâche
     la fonction 'route' utilise un nom de route
     'csrf_field' ajoute un champ caché qui permet de vérifier
       que le formulaire vient du serveur.
  --}}

<form action="{{route('jeux.store')}}" method="POST">
    {!! csrf_field() !!}
    <div class="text-center" style="margin-top: 2rem">
        <h3>Ajout d'un jeu</h3>
        <hr class="mt-2 mb-2">
    </div>
    <div>
        {{-- la date d'expiration  --}}
        <label for="nj"><strong>Nom du jeu : </strong></label>
        <input type="text" name="nom" id="nj"
               value="{{ old('nom') }}"
               placeholder="Nom du Jeu">
    </div>
    <div>
        {{-- la catégorie  --}}
        <label for="as"><strong>Année de Sortie</strong></label>
        <input type="text" class="form-control" id="as" name="annee_sortie"
               value="{{ old('annee_sortie') }}">
    </div>
    <div>
        {{-- la catégorie  --}}
        <label for="am"><strong>Age minimal</strong></label>
        <input type="text" class="form-control" id="am" name="age_min"
               value="{{ old('age_min') }}">
    </div>
    <div>
        {{-- la catégorie  --}}
        <label for="mmj"><strong>Joueur Min / Max</strong></label>
        <input type="text" class="form-control" id="mmj" name="min_max_joueur"
               value="{{ old('min_max_joueur') }}">
    </div>
    <div>
        {{-- la catégorie  --}}
        <label for="mmd"><strong>Durée Min / Max</strong></label>
        <input type="text" class="form-control" id="mmd" name="min_max_duree"
               value="{{ old('min_max_duree') }}">
    </div>
    <div>
        {{-- la catégorie  --}}
        <label for="iu"><strong>Url Image</strong></label>
        <input type="text" class="form-control" id="iu" name="urlimg"
               value="{{ old('urlimg') }}">
    </div>
    <div>
        <label for="textarea-input"><strong>Description :</strong></label>
        <textarea name="description" id="description" rows="6" class="form-control"
                  placeholder="Description..">{{ old('description') }}</textarea>
    </div>
    <div>
        <button class="btn btn-success" type="submit">Valide</button>
    </div>
</form>
</div>
    @endsection

resources/views/jeux/edit.blade.php
{{--
   messages d'erreurs dans la saisie du formulaire.
--}}
@extends('layouts.header')
@section("content")
<div class="container">
    {{--
       messages d'erreurs dans la saisie du formulaire.
    --}}


    @if ($errors->any())
        <div>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {{--
         formulaire de saisie d'une tâche
         la fonction 'route' utilise un nom de route.
         '@csrf' ajoute un champ caché qui permet de vérifier
           que le formulaire vient du serveur.
         '@method('PUT') précise à Laravel que la requête doit être traitée
          avec une commande PUT du protocole HTTP.
      --}}
    <form action="{{route('jeux.update',$jeux->id)}}" method="POST">
        @csrf
        @method('PUT')
       <div class="text-center" style="margin-top: 2rem">
            <h3>Modification d'un jeu</h3>
            <hr class="mt-2 mb-2">
        </div>
        <div>
            {{-- la date d'expiration  --}}
            <label for="nj"><strong>Nom du jeu : </strong></label>
            <input type="text" name="nom" id="nj"
                   value="{{  $jeux->nom }}"
                   placeholder="Nom du Jeu">
        </div>
        <div>
            {{-- la catégorie  --}}
            <label for="as"><strong>Année de Sortie</strong></label>
            <input type="text" class="form-control" id="as" name="annee_sortie"
                   value="{{ $jeux->annee_sortie }}">
        </div>
        <div>
            {{-- la catégorie  --}}
            <label for="am"><strong>Age minimal</strong></label>
            <input type="text" class="form-control" id="am" name="age_min"
                   value="{{ $jeux->age_min }}">
        </div>
        <div>
            {{-- la catégorie  --}}
            <label for="mmj"><strong>Joueur Min / Max</strong></label>
            <input type="text" class="form-control" id="mmj" name="min_max_joueur"
                   value="{{ $jeux->min_max_joueur }}">
        </div>
        <div>
            {{-- la catégorie  --}}
            <label for="mmd"><strong>Durée Min / Max</strong></label>
            <input type="text" class="form-control" id="mmd" name="min_max_duree"
                   value="{{ $jeux->min_max_duree }}">
        </div>
        <div>
            {{-- la catégorie  --}}
            <label for="iu"><strong>Url Image</strong></label>
            <input type="text" class="form-control" id="iu" name="urlimg"
                   value="{{ $jeux->urlimg }}">
        </div>
        <div>
            <label for="textarea-input"><strong>Description :</strong></label>
            <textarea name="description" id="description" rows="6" class="form-control"
                      placeholder="Description..">{{ $jeux->description }}</textarea>
        </div>
        <div>
            <button class="btn btn-success" type="submit">Valide</button>
        </div>
    </form>
</div>
@endsection

resources/views/jeux/index.blade.php
@extends('layouts.header')
@section('content')


<div class="container">
    <h1>Liste des jeux</h1>
    @if(!empty($jeux))
    <br>
    <div class="row">
        @foreach($jeux as $jeu)
            @if($jeu['id'] % 2 == 1 && $jeu['id'] != 1)
                </div>
                <br>
                <div class="row">
            @endif
                <div class="col">
                    <div class="card" style="width:400px">
                        <img class="card-img-top" src="{{$jeu['urlimg']}}"  style="height:100px;object-fit: cover;" alt="Card image">
                        <div class="card-body">
                            <h4 class="card-title">{{$jeu['nom']}}</h4>
                            <h5>Année Sortie : {{$jeu['annee_sortie']}}</h5>
                            <h5>Age Mini : {{$jeu['age_min']}} ans</h5>
                            <h5>Nombre joueurs : {{$jeu['min_max_joueur']}}</h5>
                            <h5>Durée : {{$jeu['min_max_duree']}}</h5>
                            <p class="card-text">{{$jeu['description']}}</p>
                            <a class="btn btn-secondary" href="{{route('jeux.show',$jeu['id'])}}">Infos</a>
                        </div>
                    </div>
                </div>
        @endforeach
                </div>
    @else
        <h2>Aucun jeu d'entré !</h2>
    @endif
</div>
@endsection

resources/views/jeux/show.blade.php
<?php


?>
@extends('layouts.header')
@section("content")

<div class="container">
    <br>
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="card" style="width:400px">
                <img class="card-img-top" src="{{$jeux->urlimg}}"  style="height:100px;object-fit: cover;" alt="Card image">
                <div class="card-body">
                    <h4 class="card-title">{{$jeux->nom}}</h4>
                    <h5>Année Sortie : {{$jeux->annee_sortie}}</h5>
                    <h5>Age Mini : {{$jeux->age_min}} ans</h5>
                    <h5>Nombre joueurs : {{$jeux->min_max_joueur}}</h5>
                    <h5>Durée : {{$jeux->min_max_duree}}</h5>
                    <p class="card-text">{{$jeux->description}}</p>
                    @if($action == 'delete')
                        <form action="{{route('jeux.destroy',$jeux->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <div class="text-center">
                                <button type="submit" name="delete" value="valide">Valider</button>
                                <button type="submit" name="delete" value="annule">Annuler</button>
                            </div>
                        </form>
                    @else
                        <div>
                            <a href="{{route('jeux.index')}}">Retour à la liste</a>
                        </div>
                    @endif


                </div>
            </div>
        </div>

    </div>
    <br>
    @if ($action != 'delete')
    <h4>Tags</h4>
        <div style="text-align: center;">
        @foreach($tags as $tag)

            <span class="badge badge-info">{{$tag['label']}}</span>

        @endforeach
        </div>
            <br>



        <h4>Commentaires</h4>
    <div class="row">

        <div class="col-sm-2"></div>
        <div class="col-sm-8">
    @if( sizeof($comm)>0)
        @foreach($comm as $commentaire)
                    <div class="card text-white bg-secondary mb-3" style="width:100%;">
                            <div class="card-header"><b>{{$commentaire['titre']}}</b> par {{$commentaire['auteur']}} le {{$commentaire['created_at']}}</div>
                            <div class="card-body">
                                {{$commentaire['body']}}
                                @if(Auth::check() && Auth::user()->name == $commentaire['auteur'] )
                                        <br><br>
                                    <a href="#" data-toggle="modal" data-target="#modEditCom{{ $commentaire['id'] }}">Éditer</a> <a href="#" data-toggle="modal" data-target="#modSuppCom{{ $commentaire['id'] }}">Supprimer</a>

                                    <!-- Modale d'édition -->
                                    <!-- Modal -->
                                    <div class="modal fade" id="modEditCom{{ $commentaire['id'] }}" tabindex="-1" role="dialog" aria-labelledby="Editer" aria-hidden="true" style="color:black;">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Éditer le commentaire</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form method="post" action="{{ route("comm.update", $commentaire["id"]) }}">
                                                    @method('PUT')
                                                <div class="modal-body">
                                                    {!! csrf_field() !!}
                                                    <label for="titcom">Titre du commentaire</label><br>
                                                    <input type="text" id="titcom" name="title" value="{{$commentaire['titre']}}" required><br>
                                                    <label for="comment">Commentaire</label>
                                                    <textarea class="form-control" rows="5" id="comment" name="comm" required>{{ $commentaire['body'] }}</textarea>
                                                    <input type="hidden" name="idjeu" value="{{$jeux->id}}">
                                                    <input type="hidden" name="aut" value="{{Auth::user()->name}}">
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal" >Fermer</button>
                                                    <button type="submit" class="btn btn-primary">Confirmer</button>
                                                </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>


                                    <!-- Modale de suppression -->
                                    <div class="modal fade" id="modSuppCom{{ $commentaire['id'] }}" style="color:black">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Supprimer le commentaire</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Êtes-vous sûr de supprimer le commentaire ?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <form method="post" action="{{ route("comm.destroy", $commentaire['id']) }}">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" type="button" name="delete" value="valid" class="btn btn-danger">Oui</button>
                                                    </form>

                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>












                                @endif
                            </div>



                    </div>

        @endforeach
    @else
                <h5>Pas de commentaire</h5>
    @endif
            <hr>
        @if(Auth::check())
            <!--  -->
            <h4>Votre commentaire !</h4>
            <form action="{{route('comm.store')}}" method="POST">
                <div class="form-group">
                    {!! csrf_field() !!}
                    <label for="titcom">Titre du commentaire</label><br>
                    <input type="text" id="titcom" name="title" placeholder="Le titre de votre commentaire" required><br>
                    <label for="comment">Commentez !</label>
                    <textarea class="form-control" rows="5" id="comment" placeholder="Votre Commentaire ici" name="comm" required></textarea>
                    <input type="hidden" name="idjeu" value="{{$jeux->id}}">
                    <input type="hidden" name="aut" value="{{Auth::user()->name}}">
                    <input type="submit" value="Envoyer">
                </div>
            </form>
        @endif
        </div>
    </div>
    @endif
</div>
@endsection